### ISSUE TITLE
Python 2 Compatibility

### ISSUE THREAD

**Issue by jhoelzl** [iSpeech/iSpeech-Python-SDK#1]
Is there also a Python 2.7 compatible SDK available? This repo only works with Python 3.

**Comment by ghost** [comment]
(Commenting as a user of this library). To be fair to the authors, Python 3 has been out for **almost a decade**! Python 2 is now in extended maintenance having not seen any updates since the final version came out almost 7 years ago in  mid-2010.

What is preventing you using the current version? You know you can install both on your system, right?

**Comment by jhoelzl** [comment]
Of course you are right, however, i have to develop software for a hardware project which only supports the Python version 2.7.9.

I suppose you don't have to change the code so much, you only have to load the correct modules, like in this library: https://github.com/Uberi/speech_recognition/blob/master/speech_recognition/__init__.py#L29:L35.

**Comment by cyberpirate** [comment]
As of now we do not support support Python 2.7. You can also use the restful api directly, the docs are located here [http://www.ispeech.org/api](http://www.ispeech.org/api). If you do decide to add 2.7 support yourself, be sure to send a pull request!
